tfg/polls/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView #esta es la vista del login
from django.contrib.auth import logout as do_logout
app_name = 'polls'

#Las siguientes direcciones se encuentran dentro de la app_name "polls"
urlpatterns = [
	#Se encuentran todas las consultas creadas
	url(r'^$', views.index, name="index"), #127.0.0.1:8000/polls/ 
	#Consulta con el id correspondiente
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name="detail"), #127.0.0.1:8000/polls/1
	#Votacion realiada
	url(r'^(?P<question_id>[0-9]+)/results$', views.results, name="results"), #127.0.0.1:8000/polls/1/results
	path('post/<int:question_id>', views.vote, name='vote'),
	#Cracion de la consulta
	path(r'createpoll/',views.createpoll,name="createpoll_url"),
	#Consulta guardada
	path(r'savedpoll/', views.savedpoll, name="savedpoll_url"), 
	#Vencedor de la consulta
	#Si no tiene participantes se elimina directamente la consulta
	url(r'^(?P<question_id>[0-9]+)/winner$', views.winner, name="winner"), 
	#Cierre de la consulta
	url(r'^(?P<question_id>[0-9]+)/closepoll$', views.closepoll, name="closepoll"), #127.0.0.1:8000/polls/1/closepoll
	#Página con el QR y el enlace a la cosulta
	url(r'(?P<question_id>[0-9]+)/qrlink$$', views.qrlink, name="qrlink"), 
	#Login
	path(r'login/',views.login,name="login_url"),
	#Registro
	path('register/',views.registerView,name="register_url"),
	#Logout
	path(r'logout/',views.logout,name="logout_url"),
	#Borrar consulta si no tiene participantes
	path('deletepoll/',views.deletepoll,name="deletepoll"),
	#Página principal
	path('',views.indexView,name='home'),
	#Página principal de interacción con el usuario registrado
	path('dashboard/',views.dashboardView,name="dashboard"),
]

tfg/tfg/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include 

#Todas las URLs a las que se pueden acceder
urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls), 
    path('polls/', include('polls.urls', namespace="polls")),
]

tfg/polls/models.py
from django.db import models
from django import forms
from datetime import datetime  
from django.contrib.postgres.forms import SimpleArrayField
import qrcode
from qrcode.image.pure import PymagingImage
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw

class Question(models.Model): #Modelo donde se encuentran todos los datos necesarios para la Consulta
	question_text = models.CharField(max_length = 100)
	pub_date = models.DateTimeField(default=datetime.now, blank = True)
	all_votations = models.CharField(max_length = 1000,  blank = True)
	participants = models.IntegerField(default = 0, blank = True)
	total_of_answers = models.IntegerField(default = 0, blank = True)
	creator = models.CharField(max_length = 100, blank = True)
	qr_code = models.ImageField(upload_to='polls/static/polls', blank=True)


	def __str__ (self):
		return self.question_text

	def save(self, *args, **kwargs):  #Creacion del código QR
		input_data = '/polls/' + str(self.id) 
		qrcode_img = qrcode.make(input_data)
		canvas = Image.new('RGB', (290,290), 'white')
		draw = ImageDraw.Draw(canvas)
		canvas.paste(qrcode_img)
		fname = f'{self.id}.png'
		buffer = BytesIO()
		canvas.save(buffer,'PNG')
		self.qr_code.save(fname, File(buffer), save=False)
		canvas.close()
		super().save(*args, **kwargs)

class Choice(models.Model): 	#Respuesta a la consulta
	choice_text = models.CharField(max_length = 200)	
	question = models.ForeignKey(Question, on_delete=models.CASCADE)	#Clave foránea de la consulta, perteneciente a la "Question" de la que proviene
										#Si se elimina la "Question" se eliminan todas las "Choice" que tenga

	def __str__ (self):
  		return self.choice_text

tfg/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse 
from django.db.models import F, Value
from django.db.models.functions import Concat
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.contrib import messages
from collections import defaultdict
import random

def indexView(request):
	return render(request, 'polls/index.html')

def login(request):

	form = AuthenticationForm()
	if request.method == "POST":
		form = AuthenticationForm(data=request.POST)

	if form.is_valid():	#Se comprueba el usuario y la contraseña

		username = form.cleaned_data['username']
		password = form.cleaned_data['password']


		user = authenticate(username=username, password=password)

		if user is not None:	#Si el usuario existe, se procede al inicio de sesión

			do_login(request, user)
			latest_questions = Question.objects.order_by('-pub_date')#[:5]	
			context =  {
			'latest_questions': latest_questions,
			}
			return render(request, 'polls/dashboard.html', context)


	return render(request, "polls/registration/login.html", {'form': form})

def logout(request):

	do_logout(request)
	form = AuthenticationForm
	return render(request, 'polls/dashboard.html',{'form':form})

def dashboardView(request):	#Vista principal de interacción del usuario registrado
	latest_questions = Question.objects.order_by('-pub_date')#[:5]	#Muestra las consultas que tiene activas y que haya creado el usuario
	question =  {
	'latest_questions': latest_questions,
	}


	return render(request, 'polls/dashboard.html',question)

def registerView(request):
	if request.method =="POST":
		form = UserCreationForm(request.POST)
		usernameNew = request.POST['username']

		if form.is_valid():	#Si el usuario se ha registrado correctamente se guarda su usuario y cintraseña 
			form.save()
			user = User.objects.get(username = usernameNew)
			user.is_staff = False
			user.is_admin = False
			user.is_superuser = True	#El usuario que se registra es superusuario para que pueda modificar la base de datos.
			user.save()
			autform = AuthenticationForm
			do_login(request, user)		#Una vez registrado también mantenemos que haya hecho el inicio de sesión
			return render(request, "polls/dashboard.html",{'form':autform})
	else:
		form = UserCreationForm()	

	return render(request, 'polls/registration/register.html',{'form':form}) #Si no se ha hecho correctamente se vuelve a la página de registro con los mensajes de error correspondientes

def index(request):	#En el index se encuentran todas las consultas creadas, pero no se utiliza esta vista para el proyecto
	latest_questions = Question.objects.order_by('-pub_date')#[:5]	
	context =  {
	'latest_questions': latest_questions,
	}
	return render(request, 'polls/index.html', context)

def qrlink(request, question_id):	#Pantalla de lectura del QR
	question = get_object_or_404(Question, pk = question_id)	
	return render(request, 'polls/qrlink.html', {'question': question})

def detail(request, question_id):
	question = get_object_or_404(Question, pk = question_id)	
	return render(request, 'polls/detail.html', {'question': question})

def closepoll(request,  question_id):	#Cierre de la consulta que se haya seleccionado
	question = get_object_or_404(Question, pk = question_id)	
	return render(request, 'polls/closepoll.html',{'question':question})

def results(request, question_id):	#Cuando se ha efectuado la votación, se muestra esta vista con un mensaje de que todo ha salido correctamente
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):		
	question = get_object_or_404(Question, pk=question_id)
	context = {
		'question': question,
	}


	maxItems = int(request.POST.get("numberOfElements", ""))
	idChoice = []
	for i in range(0, maxItems): #Con este for conseguimos todos los ID
		elem = str("choiceSelected") + str(i+1)
		idChoice.append(request.POST.get(elem,""))

	
	valueArray = [] #almacena en un array las values de todas las respuestas
	for j in range(0, maxItems):
		auxElem =  str("choice") + str(idChoice[j])
		valueArray.append(str(request.POST.get(auxElem,"")))
		
	for x in range(0, maxItems):#comprobar elementos repetidos
		for w in range(x+1, maxItems):
			if valueArray[x] == valueArray[w]:
				return render(request, 'polls/detail.html', {'question': question, 'error_message': "No se pueden repetir las opciones seleccionadas"})

	for a in range(0, maxItems):#almacenar respuestas
		for b in range(0, maxItems):
			if a+1 == int(valueArray[b]):
				question.all_votations += (str(idChoice[b]))
				question.all_votations += ','

	question.participants += 1
	question.total_of_answers += int(maxItems)
	question.save()


	return render(request,'polls/results.html', {'question': question})

def createpoll(request):
	return render(request, 'polls/createpoll.html', )

def deletepoll(request):	#Eliminación de la consulta si no ha tenido ningún participante
	return render(request, 'polls/deletepoll.html', )

def savedpoll(request):		#Creación de la consulta
	#Se tienen en cuenta una serie de controles de errores para que se pueda guardar correctamente la votación

	if not request.user.is_authenticated:
		messages.error(request, 'Tiene que estar registrado para crear una consulta')
		return render(request, 'polls/createpoll.html',)

	
	usernamePoll = str((request.POST.get("userName",""))) 	
	n = random.randint(0,1000)
	question_text = str((request.POST.get("questionName",""))) 
	if question_text == "":
		messages.error(request, 'Tiene que rellenar el nombre de la consulta')
		return render(request, 'polls/createpoll.html',)
	question = Question(n,question_text)
	question.creator = str(request.user.get_username())

	question.save()

	count = int((request.POST.get("count",""))) 
	for a in range(1, count):
		aux = str("textbox") + str(a)
		currentChoice = str((request.POST.get(aux,""))) 
		if currentChoice == "":
			messages.error(request, 'Tiene que rellenar los campos de las opciones')
			question.delete()
			return render(request, 'polls/createpoll.html',)
		choice = Choice(n+int(a),currentChoice,n)
		choice.save()

	
	
	return render(request, 'polls/savedpoll.html', {'question': question})


def winner(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	if question.participants != 0:	
		num_participants = int(question.participants)   		#numero de participantes en la encuesta
	else:
		question.delete()
		return render(request, 'polls/deletepoll.html', )
	aux_list = (question.all_votations).split(',')
	num_votes = int(question.total_of_answers)				#numero de votos emitidos
	

	results_elements_in_matrix = int(num_votes / num_participants)		#numero de choices de la pregunta
	
	if results_elements_in_matrix == 1:
		question.delete()
		return render(request, 'polls/deletepoll.html', )

	lista_nueva = []
	for i in range(0, len(aux_list), results_elements_in_matrix):
	    lista_nueva.append(aux_list[i:i+results_elements_in_matrix])  	#almacena en una lista todas las respuestas ordenadas
	lista_nueva.pop() 							#elimina el ultimo elemento el cual es una lista vacía


	matrix_of_distances = []						#calculo de la matriz de distancias
	elem_evaluated = str( int(question_id )+ 1)
	distance = 0


	for a in range(0,results_elements_in_matrix):
		for i in range(0,num_participants):
			for j in range(0,results_elements_in_matrix):	
				if elem_evaluated != lista_nueva[i][j]:
					
					matrix_of_distances.append(elem_evaluated)
					matrix_of_distances.append(lista_nueva[i][j])
					for o in range(0,results_elements_in_matrix):	
						if elem_evaluated == lista_nueva[i][o]:
							pos_elem_evaluated = o
					aux= j - pos_elem_evaluated		#calculamos la distancia entre el elemento evaluado y el otro elemento con el que se compara
					if aux < 0:		
						aux = 0;			
					matrix_of_distances.append(str(aux))
		elem_evaluated = str( int(elem_evaluated )+ 1)

	matrix_of_distances_aux = []
	for i in range(0, len(matrix_of_distances), 3):				#se separa de 3 en 3 ya que tenemos [id1, id2, distancia]
	    matrix_of_distances_aux.append(matrix_of_distances[i:i+3])  	
	matrix_of_distances_aux.pop() 

	matrix_of_distances = matrix_of_distances_aux        			#con esto conseguimos la matriz al separar los resultados de la lista en una matriz.
	
	for i in range(0,len(matrix_of_distances)):
		for j in range(0,len(matrix_of_distances)):	
			if i != j:
				if matrix_of_distances[i][0] == matrix_of_distances[j][0]:
					if matrix_of_distances[i][1] == matrix_of_distances[j][1]:
						matrix_of_distances[i][2] = str(int(matrix_of_distances[i][2]) + int(matrix_of_distances[j][2]))     #suma el elemento numero 3 de la lista que es la distancia
						matrix_of_distances[j][0]= '.'		#pone el primer elemento a "." para no volver a hacer la comparación y eliminarlo posteriormente
						

	
	for i in range(len(matrix_of_distances)-1,0,-1):
		if matrix_of_distances[i][0] == '.':
			matrix_of_distances.pop(i)				#elimina todos los elementos que tengan como primer elemento un "."
	
	grafo = matrix_of_distances						#generacion del grafo

	for i in range(0,len(grafo)):
		for j in range(0,len(grafo)):
			if i != j:
				if grafo[i][0] == grafo[j][1] and grafo[i][1] == grafo[j][0]:
					grafo[i][2] = str(int(grafo[i][2]) - int(grafo[j][2]))
					grafo[j][0] = '.'
	
	for i in range(len(grafo)-1,0,-1):					#eliminar elementos sobrantes
		if grafo[i][0] == '.':	
			grafo.pop(i)


	for i in range(0,len(grafo)):
		if (int(grafo[i][2]) < 0):
			aux1 = grafo[i][0] 
			aux2 = grafo[i][1] 
			grafo[i][0] = aux2

tfg/polls/templates/polls/base.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Base</title>
<!Título de la página>
<!Este base estará presente en todas las pantallas de /polls>
<h1 align="center"> <a href="../../">Trabajo final de grado.</a></h1>
<h2 align="center"> Aplicación web para consultas utilizando el método Schulze</h2>
  </head>
  <!Se establece el fondo de todas las páginas>
  <body style="background-color:rgb(190,230,240);">
   <hr> 
    
    <!Se comprueba si el usuario ha iniciado sesión>
    {% if user.username != "" %}  
	<p align="right"> <strong> Usuario: </strong> {{user.username}}    
	<p align="right"><a href="/polls/logout"><input type="button" value="Log out"/></a></p></p>
	<input type="hidden" name="userName" value="{{ user.username }}">
    {% endif %}

	<!Incluye el main_content y el footer>
  	{% block main_content %}
	{% endblock %}
  
	{% include "polls/footer.html" %}
	
  </body>
</html>

tfg/polls/templates/polls/closepoll.html
{% extends 'polls/base.html' %}

<!Esta página permite la posibilidad al usuario creador de la consulta de cerrar la consulta, o de por contrario mostrar el enlace a la misma o volver al Home de la aplicación>
{% block main_content %}
	<h3>A continuación podrá hacer las siguientes acciones con su consulta: "<b>{{ question.question_text }}</b>"</b>? </h3>
	<p>Link y QR de la consulta "<b>{{ question.question_text }}</b>": <a href="/polls/{{ question.id }}/qrlink">localhost:8000/polls/{{ question.id }}/qrlink</a></p>


	<li>A continuación podrá dar por finalizada la consulta y mostrar el vencedor: <a href = "/polls/{{ question.id }}/winner"><b>Cerrar</b></a></p<li>
	<li>Si desea volver al home: <a href = "/"><b>Volver al home</b></a></p></li>
{% endblock %}

tfg/polls/templates/polls/createpoll.html
{% extends 'polls/base.html' %}

{% block main_content %}
<!Esta pantalla pertenece a la creación de la consulta>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!Se introduce el título de la consulta y las opciones de la misma>
    <h1>Cree una consulta</h1>
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
		{{ message }}
	    </li>
	    {% endfor %}
	</ul>

	<form action = "../savedpoll/" method="post">
	{% csrf_token %}
	<!El código del javascript está basado en el siguiente que se encuentra en el siguiente enlace:> 
	<!https://es.coredump.biz/questions/23563141/how-to-add-auto-complete-json-for-dynamically-generated-textboxes-in-aspnet#23563313>
   	<p>Título: <input type="text" name="questionName" ></p>

	<style type="text/css">
	div{
	    padding:6px;	
	}
	</style>


	<script type="text/javascript">

	$(document).ready(function(){

	var counter = 2;

	$("#addButton").click(function () {
	var newTextBoxDiv = $(document.createElement('div'))
	     .attr("id", 'TextBoxDiv' + counter);

	<!-- De esta manera le pasamos el contenido de cada Choice -->
	newTextBoxDiv.after().html('<label>Opción #'+ counter + ' : </label>' +
	      '<input type="text" name="textbox' + counter + 
	      '" id="textbox' + counter + '" value="" >');        			

	newTextBoxDiv.appendTo("#TextBoxesGroup");


	counter++;
 	document.getElementById('i').value = counter;	
	 });

	<!-- Se eliminan los botones de la siguiente manera -->
	 $("#removeButton").click(function () {
	if(counter==1){
	      alert("No more textbox to remove");
	      return false;
	   }   

	counter--;

	    $("#TextBoxDiv" + counter).remove();
 	document.getElementById('i').value = counter;	
	 });

	  });

	</script>

	<!Se le pasan al views el ID de las consultas>
	<input type="hidden" id="i" value= "0" name="count"></input>
	<div id='TextBoxesGroup'>

	<div id="TextBoxDiv1">
	    <label>Opción #1 : </label><input type='textbox' id='textbox1' name='textbox1'>
	</div>
	</div>
	<input type='button' value='Añadir nueva opción' id='addButton'>
	<input type='button' value='Eliminiar última opción' id='removeButton'>
        <input type="reset" value="Restaurar consulta">		
    <p>
        <input type="submit" value="Enviar datos">



</form>

    </p>



{% endblock %}

tfg/polls/templates/polls/dashboard.html
{% extends 'polls/base.html' %}


{% block main_content %}
	
	<!Se muestra de diferente manera esta pantalla en función de si el usuario ha iniciado sesión o si la ha cerrado>
	<!Si inicia sesión se permite ver las consultas que tenga activas este usuario o crear una nueva consulta!>
	{% if user.username != "" %}
       	<h2>User: {{user.username}}</h2>
		<p>Cree una encuesta: <a href="../createpoll">Crear</a></p>


		{% if latest_questions != NULL %}
			{% for question in latest_questions %}
				{% if question.creator == user.username %}
					<li><a href = "/polls/{{ question.id }}/closepoll"><b>{{question.question_text}}</b></a></li>	
				{% endif %}
			{% endfor %}
			</ul>
		{% endif %}
   
	<!Si cierra sesión, se le notifica>
	{% else %}

	
		<h1>Cierre de sesión realizado correctamente</h1>
		<p> Volver al inicio <a href="/">aquí</a></p>

	{% endif %}



	 
{% endblock %}

tfg/polls/templates/polls/deletepoll.html
{% extends 'polls/base.html' %}

{% block main_content %}

<!Esta página aparecerá si se ha cerrado una consulta que no tenga participantes o si solamente tiene una Choice>
<h1 style ="color:darkred"> Se ha eliminado correctamente su consulta. </h1>
<p> Su consulta no tiene  vencedor porque no ha tenido ningún participante o sólo tenía un candidato</p>
	<li> Volver al inicio <a href="/">aquí</a></li>
{% endblock %}

tfg/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
 	
<!Esta página permite responder a la consulta>
{% block main_content %}
   <h1 style ="color:darkblue"> {{question.question_text}} </h1>



<! Muestra mensaje de error si se hubiese realizado la consulta de manera incorrecta>
{% if error_message %} <p>{{error_message}}</p> 
{% endif %}

<p> </p>


<form action = "{% url 'polls:vote' question.id %}" method="post"> <!Post: Solicita que un servidor web acepte los datos incluidos en el cuerpo del mensaje>
<p><b>Considere la opción más a la izquierda como la de mayor prioridad: </b></p>
	{% csrf_token %}       <!para modificar datos>
	<!Se tienen tantos "Button type radio" como "Choices" haya tanto en filas como en columnas>
	{% for choice in question.choice_set.all %}
	
		{% for question in question.choice_set.all %}

			<input  type="radio" name="choice{{ choice.id }}" required  value="{{ forloop.counter }}"> 

		{% endfor %}

	<!Corresponde al texto de cada opción>
	<lable for="choice{{forloop.counter}}"> {{choice.choice_text}} </label> <br>
	
	<!Corresponde al número de opciones que hay que se incrementa en cada iteración del bucle>
	<input type="hidden" name="numberOfElements" value="{{ forloop.counter }}">

	<!Se le está pasando el nombre de la opcion seleccionada con el numero del ID al que corresponde>
	<input type="hidden" name="choiceSelected{{ forloop.counter }}" value="{{ choice.id }}">

	{% endfor %}



<p> </p>
<p> </p>
	<input type="submit"value="votar"/>
</form>





{% endblock %}

tfg/polls/templates/polls/footer.html
<hr>
<!El footer estará presente en todas las páginas de la aplicación>
<p align="right"> <b>Realizado por:</b> Andrés Alcántara Alcántara </p>
</hr>

tfg/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

    {% if latest_questions %}
	<ul>
		{% for question in latest_questions %}
			<li><a href = {% url "polls:detail" question.id %}><b>{{question.question_text}}</b></a></li>
		{% endfor %}
	</ul>
    {% else %}
	<p> No tiene ninguna consulta. Cree alguna para que se muestre en la pagina actual. </p>
    {% endif %}

{% endblock %}

tfg/polls/templates/polls/qrlink.html
<!doctype html>
<html lang="es">
 
<!Esta página es la única que no tiene ni footer ni header>
<!Es una pantalla simple con un fondo negro para hacer resaltar mejor la imagen QR>
  <body style="background-color:rgb(0,0,0);">
  
<!Se cargan las imágenes que se encuentran en el fichero "static">
{% load static %}

<p align="center" ><a href="/polls/{{ question.id }}"> <b style ="color:white">localhost:8000/polls/{{ question.id }}</a></b></p>
  <p align="center"><img src="{% static 'polls/' %}{{ question.id }}.png"></p>
<p align="center" ><b style ="color:white">Si desea volver al home: <a href = "/"><b>Volver al home</b></a></p></p>



  </body>
</html>

tfg/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}
<!Una vez realizada la consulta, se muestra un mensaje de que se ha realizado correctamente>
<h1> Gracias por parcicipar en la consulta:  "{{question.question_text}}" </h1>
	<li>Sus resultados han sido guardados.</li>
	<p>Espere a que le proporcionen los resultados de la consulta.</p>
{% endblock %}

tfg/polls/templates/polls/savedpoll.html
{% extends 'polls/base.html' %}
{% load static %}
{% block main_content %}

<!Una vez guardados todos lo campos de la consulta, se muestra el link para su acceso, y el enlace a la página que nos muestra el QR y el link>

    <h1>Consulta creada</h1>

<p>Link de la consulta "<b>{{ question.question_text }}</b>": <a href="/polls/{{ question.id }}">localhost:8000/polls/{{ question.id }}</a></p>
<p>QR: <a href="/polls/{{ question.id }}/qrlink">localhost:8000/{{ question.id }}/qrlink</a></p>

{% endblock %}

tfg/polls/templates/polls/winner.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1 style ="color:darkgreen"> La consulta "{{consulta}}" ha finalizado</h1>




		<li>{{lista_nueva}}</li>
		<li>{{matrix_of_distances}}</li>
		<li>{{sorted_wins}}</li>



		<!Se muestra el vencedor de la consulta>
		<p>El vencedor de la consulta por el método Schulze es: <b style ="color:darkblue">{{vencedorSchulze}}</b></p>
<p>Gracias por participar</p>

{% endblock %}